x-spark-common: &spark-common
  image: apache/spark:3.5.1
  volumes:
    - ./data:/opt/data
    - ./spark/jars/postgresql-42.2.23.jar:/opt/spark/jars/postgresql-42.2.23.jar
    - ./spark/jars/clickhouse-jdbc-0.9.8-all.jar:/opt/spark/jars/clickhouse-jdbc-0.9.8-all.jar
    - ./spark/jars/trino-jdbc-472.jar:/opt/spark/jars/trino-jdbc-472.jar
    - ./spark/jars/hadoop-aws-3.3.4.jar:/opt/spark/jars/hadoop-aws-3.3.4.jar
    - ./spark/jars/aws-java-sdk-bundle-1.12.262.jar:/opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar
    - ./spark/jars/spark-connect_2.12-3.5.1.jar:/opt/spark/jars/spark-connect_2.12-3.5.1.jar
  networks:
    - lakehouse

x-spark-worker-common: &spark-worker-common
  <<: *spark-common
  depends_on:
    - spark-master
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_WORKER_MEMORY=1g
    - SPARK_WORKER_CORES=1
  command: >
    /opt/spark/bin/spark-class
    org.apache.spark.deploy.worker.Worker
    spark://spark-master:7077


services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    ports:
      - 8081:8080
      - 7077:7077
      - 4040:4040 # -- нужно если мы хотим запустить Spark UI(это означает что Spark Driver запустился на мастере) на мастере
    environment:
      - SPARK_MODE=master
    command:
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

  spark-worker-1:
    <<: *spark-worker-common
    container_name: spark-worker-1

  spark-worker-2:
    <<: *spark-worker-common
    container_name: spark-worker-2

  spark-worker-3:
    <<: *spark-worker-common
    container_name: spark-worker-3

networks:
  lakehouse:
    name: lakehouse
    driver: bridge
