services:
  spark-client:
    image: apache/spark:3.5.1
    container_name: spark-client
    ports:
      - 4041:4041
    volumes:
      - ./data:/opt/data
      - ./pyspark:/opt/pyspark
      - ./spark/jars/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
      - ./spark/jars/clickhouse-jdbc-0.9.8-all.jar:/opt/spark/jars/clickhouse-jdbc-0.9.8-all.jar
      - ./spark/jars/trino-jdbc-472.jar:/opt/spark/jars/trino-jdbc-472.jar
      - ./spark/jars/hadoop-aws-3.3.4.jar:/opt/spark/jars/hadoop-aws-3.3.4.jar
      - ./spark/jars/iceberg-spark-runtime-3.5_2.12-1.6.1.jar:/opt/spark/jars/iceberg-spark-runtime-3.5_2.12-1.6.1.jar
      - ./spark/jars/aws-crt-client-2.20.160.jar:/opt/spark/jars/aws-crt-client-2.20.160.jar
      - ./spark/jars/bundle-2.20.160.jar:/opt/spark/jars/bundle-2.20.160.jar
      - ./spark/jars/aws-java-sdk-bundle-1.12.262.jar:/opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar
    environment:
      - SPARK_MODE=client
    command: tail -f /dev/null
    networks:
      - lakehouse

networks:
  lakehouse:
    name: lakehouse
    driver: bridge
