spark.sql.extensions                      org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.gold                    org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.gold.type               jdbc
spark.sql.catalog.gold.uri                jdbc:postgresql://postgres:5432/metastore?socketTimeout=30&connectTimeout=15
spark.sql.catalog.gold.jdbc.driver-class  org.postgresql.Driver
spark.sql.catalog.gold.jdbc.user            postgres
spark.sql.catalog.gold.jdbc.password        postgres
spark.sql.catalog.gold.catalog-name       gold
spark.sql.catalog.gold.warehouse          s3a://gold/jdbc
spark.sql.catalog.gold.io-impl            org.apache.iceberg.hadoop.HadoopFileIO
